BUN_NAME = "black bun"
BUN_PRICE = 100
BUN_NAME2 = "white bun"
BUN_PRICE2 = 200
BUN_NAME3 ="red bun"
BUN_PRICE3 = 300
INGREDIENT_TYPE_SAUCE = 'SAUCE'
INGREDIENT_TYPE_FILLING = 'FILLING'
INGREDIENT_SOUSE_1 = "hot sauce"
INGREDIENT_FILLING_1 = "cutlet"

