BUN_NAME = "black bun"
BUN_PRICE = 100
BUN_NAME2 = "white bun"
BUN_PRICE2 = 200
BUN_NAME3 ="red bun"
BUN_PRICE3 = 300
INGREDIENT_TYPE_SAUCE = 'SAUCE'
INGREDIENT_TYPE_FILLING = 'FILLING'
INGREDIENT_SOUSE_1 = "hot sauce"
INGREDIENT_SOUSE_2 = "ketchup"
INGREDIENT_FILLING_1 = "cutlet"

ingredient_data = [
    (INGREDIENT_TYPE_SAUCE, INGREDIENT_SOUSE_1, 10.0),
    (INGREDIENT_TYPE_FILLING, INGREDIENT_FILLING_1, 30.0),
    (INGREDIENT_TYPE_SAUCE, INGREDIENT_SOUSE_2, 8.0),
]

bun_data = [
        (BUN_NAME, 100),
        (BUN_NAME2, 200),
        (BUN_NAME3, 300),
    ]